return {
  --Contrib Modules
  { name = "aerial", "stevearc/aerial.nvim", require "plugins.contrib.nvim-aerial" },
  { name = "alien", "joeyfitzpatrick/alien.nvim", require "plugins.contrib.nvim-alien", lazy = false },
  { name = "arrow", "otavioschwanck/arrow.nvim", require "plugins.contrib.nvim-arrow" },
  { name = "asdf", "bry-guy/asdf-lsp.nvim", require "plugins.contrib.nvim-asdf" },
  { name = "autoclose", "m4xshen/autoclose.nvim", require "plugins.contrib.nvim-autoclose" },
  { name = "barbecue", "utilyre/barbecue.nvim", require "plugins.contrib.nvim-barbecue" },
  {
    name = "better-comments",
    "Djancyp/better-comments.nvim",
    require "plugins.contrib.nvim-better-comments",
  },
  {
    name = "better-escape",
    "max397574/better-escape.nvim",
    require "plugins.contrib.nvim-better-escape",
  },
  { name = "betterquit", "Dillonb/betterquit.nvim", require "plugins.contrib.nvim-betterquit" },
  { name = "bigfile", "LunarVim/bigfile.nvim", require "plugins.contrib.nvim-bigfile" },
  { name = "ccc", "uga-rosa/ccc.nvim", require "plugins.contrib.nvim-ccc" },
  {
    name = "clipboard-history",
    "royanirudd/clipboard-history.nvim",
    require "plugins.contrib.nvim-clipboard-history",
  },
  { name = "colorizer", "norcalli/nvim-colorizer.lua", require "plugins.contrib.nvim-colorizer" },
  {
    name = "colorpicker",
    "tribhuwan-kumar/NVIMColorPicker",
    require "plugins.contrib.nvim-colorpicker",
  },
  { name = "commander", "FeiyouG/commander.nvim", require "plugins.contrib.nvim-commander" },
  { name = "conform", "stevearc/conform.nvim", require "plugins.contrib.nvim-conform" },
  { name = "ctrlsf", "dyng/ctrlsf.vim", require "plugins.contrib.nvim-ctrlsf", lazy = false },
  { name = "ctrlsf-ui", "P4Cu/ctrlsf-ui.nvim", require "plugins.contrib.nvim-ctrlsf-ui" },
  { name = "devtools", "muhfaris/devtools.nvim", require "plugins.contrib.nvim-devtools" },
  { name = "dial", "monaqa/dial.nvim", require "plugins.contrib.nvim-dial" },
  { enabled = true, name = "diffview", "sindrets/diffview.nvim", require "plugins.contrib.nvim-diffview" },
  { enabled = true, name = "direnv", "NotAShelf/direnv.nvim", require "plugins.contrib.nvim-direnv" },
  {
    enabled = true,
    name = "dressing",
    "stevearc/dressing.nvim",
    require "plugins.contrib.nvim-dressing",
    lazy = false,
  },
  { enabled = true, name = "dropbar", "Bekaboo/dropbar.nvim", require "plugins.contrib.nvim-dropbar" },
  {
    enabled = true,
    name = "early-retirement",
    "chrisgrieser/nvim-early-retirement",
    require "plugins.contrib.nvim-early-retirement",
  },
  { enabled = true, name = "easyword", "vanaigr/easyword.nvim", require "plugins.contrib.nvim-easyword" },
  { enabled = true, name = "emmet", "olrtg/nvim-emmet", require "plugins.contrib.nvim-emmet" },
  { enabled = true, name = "eyeliner", "jinh0/eyeliner.nvim", require "plugins.contrib.nvim-eyeliner" },
  { enabled = true, name = "fidget", "j-hui/fidget.nvim", require "plugins.contrib.nvim-fidget" },
  { enabled = true, name = "formatter", "seblyng/nvim-formatter", require "plugins.contrib.nvim-formatter" },
  { enabled = true, name = "gitignore", "wintermute-cell/gitignore.nvim", require "plugins.contrib.nvim-gitignore" },
  {
    enabled = true,
    name = "grug-far",
    "MagicDuck/grug-far.nvim",
    require "plugins.contrib.nvim-grug-far",
    lazy = false,
  },
  { enabled = true, name = "guess-indent", "nmac427/guess-indent.nvim", require "plugins.contrib.nvim-guess-indent" },
  { enabled = true, name = "hologram", "edluffy/hologram.nvim", require "plugins.contrib.nvim-hologram" },
  {
    enabled = true,
    name = "hologram-math",
    "Vaisakhkm2625/hologram-math-preview.nvim",
    require "plugins.contrib.nvim-hologram-math",
  },
  { enabled = true, name = "image", "3rd/image.nvim", require "plugins.contrib.nvim-image" },
  { enabled = true, name = "inc-rename", "smjonas/inc-rename.nvim", require "plugins.contrib.nvim-inc-rename" },
  { enabled = true, name = "json", "Sup3Legacy/json.nvim", require "plugins.contrib.nvim-json" },
  { enabled = true, name = "lazydev", "folke/lazydev.nvim", require "plugins.contrib.nvim-lazydev" },
  { enabled = true, name = "lint", "mfussenegger/nvim-lint", require "plugins.contrib.nvim-lint" },
  { enabled = true, name = "lua-rocks", "vhyrro/luarocks.nvim", require "plugins.contrib.nvim-luarocks" },
  { enabled = true, name = "mapx", "b0o/mapx.nvim", require "plugins.contrib.nvim-mapx" },
  {
    enabled = true,
    name = "markdown",
    "MeanderingProgrammer/render-markdown.nvim",
    require "plugins.contrib.nvim-markdown",
    lazy = false,
  },
  {
    enabled = true,
    name = "markdown-preview",
    "iamcco/markdown-preview.nvim",
    require "plugins.contrib.nvim-markdown-preview",
    lazy = false,
  },
  { enabled = true, name = "marks", "chentoast/marks.nvim", require "plugins.contrib.nvim-marks" },
  { enabled = true, name = "marksman", "artempyanykh/marksman", require "plugins.contrib.nvim-marksman" },
  -- {
  --   enabled = false,
  --   name = "md-img-insert",
  --   "junaydb/md-img-insert.nvim",
  --   require "plugins.contrib.nvim-md-img-insert",
  -- },
  { enabled = true, name = "mistake", "ck-zhang/mistake.nvim", require "plugins.contrib.nvim-mistake" },
  {
    enabled = true,
    name = "modicator",
    "mawkler/modicator.nvim",
    require "plugins.contrib.nvim-modicator",
    lazy = false,
  },
  { enabled = true, name = "multicursor", "jake-stewart/multicursor.nvim", require "plugins.contrib.nvim-multicursor" },
  { enabled = true, name = "namespace", "ccaglak/namespace.nvim", require "plugins.contrib.nvim-namespace" },
  { enabled = true, name = "neoclip", "AckslD/nvim-neoclip.lua", require "plugins.contrib.nvim-neoclip" },
  { enabled = true, name = "neocolumn", "parmeniong/neocolumn.nvim", require "plugins.contrib.nvim-neocolumn" },
  { enabled = true, name = "neogen", "danymat/neogen", require "plugins.contrib.nvim-neogen" },
  { enabled = true, name = "neogit", "NeogitOrg/neogit", require "plugins.contrib.nvim-neogit", lazy = false },
  { name = "neominimap", "Isrothy/neominimap.nvim", require "plugins.contrib.nvim-neominimap" },
  { enabled = true, name = "neoscroll", "karb94/neoscroll.nvim", require "plugins.contrib.nvim-neoscroll" },
  { enabled = true, name = "neotab", "kawre/neotab.nvim", require "plugins.contrib.nvim-neotab" },
  { enabled = true, name = "noice", "folke/noice.nvim", require "plugins.contrib.nvim-noice" },
  { enabled = true, name = "none-ls", "nvimtools/none-ls.nvim", require "plugins.contrib.nvim-nonels" },
  {
    enabled = true,
    name = "nui-components",
    "grapp-dev/nui-components.nvim",
    require "plugins.contrib.nvim-nui-components",
  },
  { enabled = true, name = "null-ls", "brain-fuel/null-ls.nvim", require "plugins.contrib.nvim-null-ls" },
  { enabled = true, name = "oil", "stevearc/oil.nvim", require "plugins.contrib.nvim-oil" },
  {
    enabled = true,
    name = "oil-gitsigns",
    "FerretDetective/oil-git-signs.nvim",
    require "plugins.contrib.nvim-oil-gitsigns",
  },
  { enabled = true, name = "oil-nerdfont", "Omochice/oil-nerdfont", require "plugins.contrib.nvim-oil-nerdfont" },
  { enabled = true, name = "overseer", "stevearc/overseer.nvim", require "plugins.contrib.nvim-overseer" },
  { enabled = true, name = "paste", "kjwsl/paste.nvim", require "plugins.contrib.nvim-paste" },
  { enabled = true, name = "praise", "theoboldalex/praise.nvim", require "plugins.contrib.nvim-praise" },
  { name = "precognition", "tris203/precognition.nvim", require "plugins.contrib.nvim-precognition" },
  { name = "project", "ahmedkhalf/project.nvim", require "plugins.contrib.nvim-project" },
  {
    name = "rainbow-delimiters",
    "HiPhish/rainbow-delimiters.nvim",
    require "plugins.contrib.nvim-rainbow-delimiters",
  },
  -- {
  --   name = "remote-nvim",
  --   "amitds1997/remote-nvim.nvim",
  --   require "plugins.contrib.nvim-remote",
  --   lazy = false,
  -- },
  { name = "renamer", "filipdutescu/renamer.nvim", require "plugins.contrib.nvim-renamer" },
  { name = "sak", "rdpopov/nvim-sak", require "plugins.contrib.nvim-sak" },
  { name = "scope", "tiagovla/scope.nvim", require "plugins.contrib.nvim-scope" },
  { name = "scratch", "LintaoAmons/scratch.nvim", require "plugins.contrib.nvim-scratch" },
  { name = "scrollview", "dstein64/nvim-scrollview", require "plugins.contrib.nvim-scrollview" },
  {
    name = "search-replace",
    "roobert/search-replace.nvim",
    require "plugins.contrib.nvim-search-replace",
    lazy = false,
  },
  {
    name = "select-multi-line",
    "Rasukarusan/nvim-select-multi-line",
    require "plugins.contrib.nvim-select-multi-line",
  },
  { name = "sensible", "basilgood/nvim-sensible", require "plugins.contrib.nvim-sensible" },
  { name = "sessions", "natecraddock/sessions.nvim", require "plugins.contrib.nvim-sessions" },
  {
    name = "session-manager",
    "The-Plottwist/nvim-session-manager",
    require "plugins.contrib.nvim-session-manager",
  },
  {
    name = "smear-cursor",
    "sphamba/smear-cursor.nvim",
    require "plugins.contrib.nvim-smear-cursor",
    lazy = false,
  },
  { name = "sudo", "denialofsandwich/sudo.nvim", require "plugins.contrib.sudo", lazy = false },
  { name = "suedit", "Grafcube/suedit.nvim", require "plugins.contrib.nvim-suedit", lazy = false },
  -- { name = "tfm", "rolv-apneseth/tfm.nvim", require "plugins.contrib.nvim-tfm", lazy = false },
  { name = "tide", "jackMort/tide.nvim", require "plugins.contrib.nvim-tide", lazy = false },
  { name = "todo-comments", "folke/todo-comments.nvim", require "plugins.contrib.nvim-todo-comments" },
  {
    name = "toggleterm.nvim",
    "akinsho/toggleterm.nvim",
    require "plugins.contrib.nvim-toggleterm",
    lazy = false,
  },
  { name = "tree-remote", "kiyoon/nvim-tree-remote.nvim", require "plugins.contrib.nvim-tree-remote" },
  { name = "treesj", "Wansmer/treesj", require "plugins.contrib.nvim-treesj" },
  { name = "trouble", "folke/trouble.nvim", require "plugins.contrib.nvim-trouble", lazy = false },
  { name = "tsugit", "mikavilpas/tsugit.nvim", require "plugins.contrib.nvim-tsugit" },
  { name = "twilight", "folke/twilight.nvim", require "plugins.contrib.nvim-twilight", lazy = false },
  { name = "ufo", "kevinhwang91/nvim-ufo", require "plugins.contrib.nvim-ufo" },
  {
    name = "ultimate-autopair",
    "altermo/ultimate-autopair.nvim",
    require "plugins.contrib.nvim-ultimate-autopair",
  },
  { name = "unception", "samjwill/nvim-unception", require "plugins.contrib.nvim-unception" },
  { name = "undotree", "jiaoshijie/undotree", require "plugins.contrib.nvim-undotree" },
  { enabled = true, name = "valign", "riku-ri/valign.nvim", require "plugins.contrib.nvim-valign" },
  { name = "yanky", "gbprod/yanky.nvim", require "plugins.contrib.nvim-yanky" },
  { name = "yazi", "Kicamon/yazi.nvim", require "plugins.contrib.nvim-yazi" },
  {
    name = "zebrazone",
    "notomo/zebrazone.nvim",
    require "plugins.contrib.nvim-zebrazone",
    lazy = false,
  },
  { name = "zen-mode", "folke/zen-mode.nvim", require "plugins.contrib.nvim-zen-mode" },
}
