return {
  --Contrib Modules
  { enabled = true, name = "aerial", "stevearc/aerial.nvim" },
  { enabled = true, name = "alien", "joeyfitzpatrick/alien.nvim" },
  { enabled = true, name = "autoclose", "m4xshen/autoclose.nvim" },
  { enabled = true, name = "barbecue", "utilyre/barbecue.nvim" },
  { enabled = true, name = "better-comments", "Djancyp/better-comments.nvim" },
  { enabled = true, name = "better-escape", "max397574/better-escape.nvim" },
  { enabled = true, name = "betterquit", "Dillonb/betterquit.nvim" },
  { enabled = true, name = "bigfile", "LunarVim/bigfile.nvim" },
  { enabled = true, name = "ccc", "uga-rosa/ccc.nvim" },
  { enabled = true, name = "clipboard-history", "royanirudd/clipboard-history.nvim" },
  { enabled = true, name = "colorizer", "norcalli/nvim-colorizer.lua" },
  { enabled = true, name = "colorpicker", "tribhuwan-kumar/NVIMColorPicker" },
  { enabled = true, name = "commander", "FeiyouG/commander.nvim" },
  { enabled = true, name = "conform", "stevearc/conform.nvim" },
  { enabled = true, name = "ctrlsf", "dyng/ctrlsf.vim", lazy = false },
  { enabled = true, name = "devtools", "muhfaris/devtools.nvim" },
  { enabled = true, name = "dial", "monaqa/dial.nvim" },
  { enabled = true, name = "diffview", "sindrets/diffview.nvim" },
  { enabled = true, name = "direnv", "NotAShelf/direnv.nvim" },
  { enabled = true, name = "dressing", "stevearc/dressing.nvim", lazy = false },
  { enabled = true, name = "dropbar", "Bekaboo/dropbar.nvim" },
  { enabled = true, name = "early-retirement", "chrisgrieser/nvim-early-retirement" },
  { enabled = true, name = "easyword", "vanaigr/easyword.nvim" },
  { enabled = true, name = "emmet", "olrtg/nvim-emmet" },
  { enabled = true, name = "eyeliner", "jinh0/eyeliner.nvim" },
  { enabled = true, name = "fidget", "j-hui/fidget.nvim" },
  { enabled = true, name = "gitignore", "wintermute-cell/gitignore.nvim" },
  { enabled = true, name = "guess-indent", "nmac427/guess-indent.nvim" },
  { enabled = true, name = "image", "3rd/image.nvim" },
  { enabled = true, name = "inc-rename", "smjonas/inc-rename.nvim" },
  { enabled = true, name = "json", "Sup3Legacy/json.nvim" },
  { enabled = true, name = "lazydev", "folke/lazydev.nvim" },
  { enabled = true, name = "lint", "mfussenegger/nvim-lint" },
  { enabled = true, name = "lua-rocks", "vhyrro/luarocks.nvim" },
  { enabled = true, name = "mapx", "b0o/mapx.nvim" },
  { enabled = true, name = "markdown", "MeanderingProgrammer/render-markdown.nvim", lazy = false },
  { enabled = true, name = "markdown-preview", "iamcco/markdown-preview.nvim", lazy = false },
  { enabled = true, name = "marks", "chentoast/marks.nvim" },
  { enabled = true, name = "marksman", "artempyanykh/marksman" },
  { enabled = true, name = "minimap", "Isrothy/neominimap.nvim" },
  { enabled = true, name = "mistake", "ck-zhang/mistake.nvim" },
  { enabled = true, name = "modicator", "mawkler/modicator.nvim", lazy = false },
  { enabled = true, name = "namespace", "ccaglak/namespace.nvim" },
  { enabled = true, name = "neoclip", "AckslD/nvim-neoclip.lua" },
  { enabled = true, name = "neocolumn", "parmeniong/neocolumn.nvim" },
  { enabled = true, name = "neogen", "danymat/neogen" },
  { enabled = true, name = "neogit", "NeogitOrg/neogit" },
  { enabled = true, name = "neoscroll", "karb94/neoscroll.nvim" },
  { enabled = true, name = "neotab", "kawre/neotab.nvim" },
  { enabled = true, name = "nerdy", "2kabhishek/nerdy.nvim" },
  { enabled = true, name = "noice", "folke/noice.nvim" },
  { enabled = true, name = "none-ls", "nvimtools/none-ls.nvim" },
  { enabled = true, name = "nui-components", "grapp-dev/nui-components.nvim" },
  { enabled = true, name = "null-ls", "brain-fuel/null-ls.nvim" },
  { enabled = true, name = "oil", "stevearc/oil.nvim" },
  { enabled = true, name = "overseer", "stevearc/overseer.nvim" },
  { enabled = true, name = "paste", "kjwsl/paste.nvim" },
  { enabled = true, name = "phptools", "ccaglak/phptools.nvim" },
  { enabled = true, name = "praise", "theoboldalex/praise.nvim" },
  { enabled = true, name = "precognition", "tris203/precognition.nvim" },
  { enabled = true, name = "project", "ahmedkhalf/project.nvim" },
  { enabled = true, name = "rainbow-delimiters", "HiPhish/rainbow-delimiters.nvim" },
  { enabled = true, name = "renamer", "filipdutescu/renamer.nvim" },
  { enabled = true, name = "sak", "rdpopov/nvim-sak" },
  { enabled = true, name = "scope", "tiagovla/scope.nvim" },
  { enabled = true, name = "scratch", "LintaoAmons/scratch.nvim" },
  { enabled = true, name = "scrollview", "dstein64/nvim-scrollview" },
  { enabled = true, name = "select-multi-line", "Rasukarusan/nvim-select-multi-line" },
  { enabled = true, name = "sensible", "basilgood/nvim-sensible" },
  { enabled = true, name = "sensions", "natecraddock/sessions.nvim" },
  { enabled = true, name = "session-manager", "The-Plottwist/nvim-session-manager" },
  { enabled = true, name = "simplefile", "Rizwanelansyah/simplyfile.nvim", lazy = false },
  { enabled = true, name = "tide", "jackMort/tide.nvim", lazy = false },
  { enabled = true, name = "todo-comments", "folke/todo-comments.nvim" },
  { enabled = true, name = "tree-remote", "kiyoon/nvim-tree-remote.nvim" },
  { enabled = true, name = "treesj", "Wansmer/treesj" },
  { enabled = true, name = "trouble", "folke/trouble.nvim" },
  { enabled = true, name = "twilight", "folke/twilight.nvim", lazy = false },
  { enabled = true, name = "ufo", "kevinhwang91/nvim-ufo" },
  { enabled = true, name = "undotree", "jiaoshijie/undotree" },
  { enabled = true, name = "vgit", "tanvirtin/vgit.nvim" },
  { enabled = true, name = "workspaces", "natecraddock/workspaces.nvim" },
  { enabled = true, name = "yanky", "gbprod/yanky.nvim" },
  { enabled = true, name = "zebrazone", "notomo/zebrazone.nvim", lazy = false },
  { enabled = true, name = "zen-mode", "folke/zen-mode.nvim" },
}
