return {
  { "echasnovski/mini.nvim" },
  { "echasnovski/mini.ai", require "plugins.mini.mini-ai", lazy = false },
  { "echasnovski/mini.align", require "plugins.mini.mini-align", lazy = false },
  { "echasnovski/mini.animate", require "plugins.mini.mini-animate", lazy = false },
  -- { "echasnovski/mini.base16",	require "plugins.mini.mini-base16" },
  { "echasnovski/mini.basics", require "plugins.mini.mini-basics", lazy = false },
  -- { "echasnovski/mini.bracketed",	require "plugins.mini.mini-bracketed" },
  { "echasnovski/mini.bufremove", require "plugins.mini.mini-bufremove" },
  -- { "echasnovski/mini.clue",	require "plugins.mini.mini-clue" },
  -- { "echasnovski/mini.colors",	require "plugins.mini.mini-colors" },
  -- { "echasnovski/mini.comment",	require "plugins.mini.mini-comment" },
  -- { "echasnovski/mini.completion",	require "plugins.mini.mini-completion" },
  { "echasnovski/mini.cursorword", require "plugins.mini.mini-cursorword", lazy = false },
  -- { "echasnovski/mini.deps",	require "plugins.mini.mini-deps" },
  -- { "echasnovski/mini.diff",	require "plugins.mini.mini-diff" },
  -- { "echasnovski/mini.doc",		require "plugins.mini.mini-doc" },
  { "echasnovski/mini.extra", require "plugins.mini.mini-extra", lazy = false },
  -- { "echasnovski/mini.files",	require "plugins.mini.mini-files" },
  -- { "echasnovski/mini.fuzzy",	require "plugins.mini.mini-fuzzy" },
  -- { "echasnovski/mini.git",		require "plugins.mini.mini-git" },
  -- { "echasnovski/mini.hipatterns",	require "plugins.mini.mini-hipatterns" },
  -- { "echasnovski/mini.hues",	require "plugins.mini.mini-hues" },
  -- { "echasnovski/mini.icons",	require "plugins.mini.mini-icons" },
  { "echasnovski/mini.indentscope", require "plugins.mini.mini-indentscope", lazy = false },
  { "echasnovski/mini.jump", require "plugins.mini.mini-jump", lazy = false },
  -- { "echasnovski/mini.jump2d",	require "plugins.mini.mini-jump2d" },
  -- { "echasnovski/mini.map",		require "plugins.mini.mini-map" },
  { "echasnovski/mini.misc", require "plugins.mini.mini-misc", lazy = false },
  -- { "echasnovski/mini.move",	require "plugins.mini.mini-move" },
  -- { "echasnovski/mini.notify",	require "plugins.mini.mini-notify" },
  { "echasnovski/mini.operators", require "plugins.mini.mini-operators", lazy = false },
  { "echasnovski/mini.pairs", require "plugins.mini.mini-pairs", lazy = false },
  -- { "echasnovski/mini.pick",	require "plugins.mini.mini-pick" },
  -- { "echasnovski/mini.sessions", 	require "plugins.mini.mini-sessions" },
  -- { "echasnovski/mini.splitjoin", 	require "plugins.mini.mini-splitjoin" },
  -- { "echasnovski/mini.starter", 	require "plugins.mini.mini-starter" },
  -- { "echasnovski/mini.statusline", 	require "plugins.mini.mini-statusline" },
  { "echasnovski/mini.surround", require "plugins.mini.mini-surround" },
  -- { "echasnovski/mini.tabline", 	require "plugins.mini.mini-tabline" },
  { "echasnovski/mini.trailspace", require "plugins.mini.mini-trailspace", lazy = false },
  -- { "echasnovski/mini.visits", 	require "plugins.mini.mini-visits" },
}
