return {

  -- Core
  { enabled = true, name = "mini.nvim", "echasnovski/mini.nvim" },
  { enabled = false, name = "mini.deps", "echasnovski/mini.deps" },
  -- Extensions
  { enabled = true, name = "mini.ai", "echasnovski/mini.ai" },
  { enabled = true, name = "mini.align", "echasnovski/mini.align", lazy = false },
  { enabled = true, name = "mini.animate", "echasnovski/mini.animate", lazy = false },
  { enabled = false, name = "mini.base16", "echasnovski/mini.base16" },
  { enabled = true, name = "mini.basics", "echasnovski/mini.basics" },
  { enabled = false, name = "mini.bracketed", "echasnovski/mini.bracketed" },
  { enabled = false, name = "mini.bufremove", "echasnovski/mini.bufremove" },
  { enabled = false, name = "mini.clue", "echasnovski/mini.clue" },
  { enabled = false, name = "mini.colors", "echasnovski/mini.colors" },
  { enabled = false, name = "mini.comment", "echasnovski/mini.comment" },
  { enabled = false, name = "mini.completion", "echasnovski/mini.completion" },
  { enabled = true, name = "mini.cursorword", "echasnovski/mini.cursorword", lazy = false },
  { enabled = false, name = "mini.diff", "echasnovski/mini.diff" },
  { enabled = false, name = "mini.doc", "echasnovski/mini.doc" },
  { enabled = true, name = "mini.extra", "echasnovski/mini.extra" },
  { enabled = false, name = "mini.files", "echasnovski/mini.files" },
  { enabled = false, name = "mini.fuzzy", "echasnovski/mini.fuzzy" },
  { enabled = false, name = "mini.git", "echasnovski/mini.git" },
  { enabled = false, name = "mini.hipatterns", "echasnovski/mini.hipatterns" },
  { enabled = false, name = "mini.hues", "echasnovski/mini.hues" },
  { enabled = false, name = "mini.icons", "echasnovski/mini.icons" },
  { enabled = false, name = "mini.indentscope", "echasnovski/mini.indentscope" },
  { enabled = true, name = "mini.jump", "echasnovski/mini.jump" },
  { enabled = false, name = "mini.jump2d", "echasnovski/mini.jump2d" },
  { enabled = false, name = "mini.map", "echasnovski/mini.map" },
  { enabled = true, name = "mini.misc", "echasnovski/mini.misc" },
  { enabled = false, name = "mini.mov", "echasnovski/mini.move" },
  { enabled = false, name = "mini.notify", "echasnovski/mini.notify" },
  { enabled = true, name = "mini.operators", "echasnovski/mini.operators" },
  { enabled = true, name = "mini.pairs", "echasnovski/mini.pairs" },
  { enabled = false, name = "mini.pick", "echasnovski/mini.pick" },
  { enabled = false, name = "mini.sessions", "echasnovski/mini.sessions" },
  { enabled = false, name = "mini.splitjoin", "echasnovski/mini.splitjoin" },
  { enabled = false, name = "mini.starter", "echasnovski/mini.starter", priority = 1000, lazy = false },
  { enabled = false, name = "mini.statusline", "echasnovski/mini.statusline" },
  { enabled = true, name = "mini.surround", "echasnovski/mini.surround" },
  { enabled = false, name = "mini.tabline", "echasnovski/mini.tabline" },
  { enabled = true, name = "mini.trailspace", "echasnovski/mini.trailspace" },
  { enabled = false, name = "mini.visits", "echasnovski/mini.visits" },
}
