return {
  "jay-babu/mason-null-ls.nvim",
  event = { "BufReadPre", "BufNewFile" },
  dependencies = {
    "williamboman/mason.nvim",
    "nvimtools/none-ls.nvim",
  },
  config = function()
    require("mason-null-ls").setup {
      ensure_installed = {
        "commitlint",
        "autotools-language-server",
        "bash-language-server",
        "css-lsp",
        "css-variables-language-server",
        "cssmodules-language-server",
        "deno",
        "editorconfig-checker",
        "emmet-language-server",
        "emmet-ls",
        "eslint-lsp",
        "eslint_d",
        "gitleaks",
        "gitlint",
        "grammarly-languageserver",
        "html-lsp",
        "htmlbeautifier",
        "htmlhint",
        "intelephense",
        "js-debug-adapter",
        "json-lsp",
        "jsonld-lsp",
        "lua-language-server",
        "markdown-oxide",
        "markdownlint",
        "node-debug2-adapter",
        "php-cs-fixer",
        "php-debug-adapter",
        "phpactor",
        "phpcbf",
        "phpcs",
        "phpmd",
        "phpstan",
        "prettier",
        "prettierd",
        "pretty-php",
        "some-sass-language-server",
        "stylelint-lsp",
        "stylua",
        "textlint",
        "ts-standard",
        "twigcs",
        "typescript-language-server",
        "unocss-language-server",
        "vim-language-server",
        "xmlformatter",
        "yaml-language-server",
        "yamlfix",
        "yamlfmt",
        "yamllint",
      },
    } -- require your null-ls config here (example below)
  end,
}
